name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: make build

      - name: Run Docker Compose up
        run: make up

      - name: Stop Docker containers
        run: make down
